// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Translator.Infrastructure.Database.Postgres;

#nullable disable

namespace Translator.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TemplateValue", b =>
                {
                    b.Property<Guid>("TemplatesId")
                        .HasColumnType("uuid")
                        .HasColumnName("templates_id");

                    b.Property<Guid>("ValuesId")
                        .HasColumnType("uuid")
                        .HasColumnName("values_id");

                    b.HasKey("TemplatesId", "ValuesId")
                        .HasName("pk_template_values");

                    b.HasIndex("ValuesId")
                        .HasDatabaseName("ix_template_values_values_id");

                    b.ToTable("TemplateValues", (string)null);
                });

            modelBuilder.Entity("Translator.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int?>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Shortcode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("shortcode");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("type_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_parent_id");

                    b.HasIndex("Shortcode")
                        .HasDatabaseName("ix_categories_shortcode");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_categories_type_id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Translator.Domain.Entities.CategoryType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_category_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_category_types_name");

                    b.ToTable("category_types", (string)null);
                });

            modelBuilder.Entity("Translator.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("UnicodeRange")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("unicode_range");

                    b.HasKey("Id")
                        .HasName("pk_languages");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_languages_code");

                    b.ToTable("languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f94df503-c396-78a4-db20-5176ca1967b6"),
                            Code = "zh",
                            IsActive = false,
                            Name = "Mandarin Chinese",
                            UnicodeRange = "4E00-9FFF;3400-4DBF;20000-2A6DF;F900-FAFF"
                        },
                        new
                        {
                            Id = new Guid("c38054cb-712e-8877-52b0-8ae1e8712775"),
                            Code = "es",
                            IsActive = false,
                            Name = "Spanish",
                            UnicodeRange = "0000-007F;0080-00FF;0100-017F"
                        },
                        new
                        {
                            Id = new Guid("383a4678-5a4a-faa4-d5fa-73e2f506ecfc"),
                            Code = "en",
                            IsActive = false,
                            Name = "English",
                            UnicodeRange = "0000-007F"
                        },
                        new
                        {
                            Id = new Guid("1e17c345-93f1-4bc7-402f-407fba9d955b"),
                            Code = "hi",
                            IsActive = false,
                            Name = "Hindi",
                            UnicodeRange = "0900-097F;A8E0-A8FF"
                        },
                        new
                        {
                            Id = new Guid("85cb2c27-ba92-e0fd-baf1-dedce0fd3ac2"),
                            Code = "ar",
                            IsActive = false,
                            Name = "Arabic",
                            UnicodeRange = "0600-06FF;0750-077F;FB50-FDFF;FE70-FEFF"
                        },
                        new
                        {
                            Id = new Guid("7c2ce330-f44c-e934-c75e-60c14c442541"),
                            Code = "pt",
                            IsActive = false,
                            Name = "Portuguese",
                            UnicodeRange = "0000-007F;0080-00FF;0100-017F"
                        },
                        new
                        {
                            Id = new Guid("84cb6da5-c243-8e5f-14b4-7b8ff1748331"),
                            Code = "bn",
                            IsActive = false,
                            Name = "Bengali",
                            UnicodeRange = "0980-09FF"
                        },
                        new
                        {
                            Id = new Guid("2069bade-06e7-4015-1385-fe1fb5a379ec"),
                            Code = "ru",
                            IsActive = false,
                            Name = "Russian",
                            UnicodeRange = "0400-04FF;0500-052F"
                        },
                        new
                        {
                            Id = new Guid("6aed2cf3-a19b-c464-b3c0-47fd1d7c882e"),
                            Code = "ja",
                            IsActive = false,
                            Name = "Japanese",
                            UnicodeRange = "3040-309F;30A0-30FF;4E00-9FFF;FF65-FF9F;3100-312F"
                        },
                        new
                        {
                            Id = new Guid("4c29c0bb-17e6-937b-2fad-9c75af2b8563"),
                            Code = "pa",
                            IsActive = false,
                            Name = "Punjabi",
                            UnicodeRange = "0A00-0A7F"
                        },
                        new
                        {
                            Id = new Guid("1531bc86-4eeb-7398-ac96-904a4a68e19e"),
                            Code = "de",
                            IsActive = false,
                            Name = "German",
                            UnicodeRange = "0000-007F;0080-00FF;0100-017F"
                        },
                        new
                        {
                            Id = new Guid("6daf947d-eacc-73d2-6bd1-d456ba3c750a"),
                            Code = "jv",
                            IsActive = false,
                            Name = "Javanese",
                            UnicodeRange = "A980-A9DF;0000-007F"
                        },
                        new
                        {
                            Id = new Guid("079217fc-0092-b705-dca8-5323ceacf5eb"),
                            Code = "ms",
                            IsActive = false,
                            Name = "Malay",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("888ab815-cfe6-a416-462c-1562fdcb0c19"),
                            Code = "te",
                            IsActive = false,
                            Name = "Telugu",
                            UnicodeRange = "0C00-0C7F"
                        },
                        new
                        {
                            Id = new Guid("e8fa807b-4056-6cc1-db02-61bef0c27636"),
                            Code = "vi",
                            IsActive = false,
                            Name = "Vietnamese",
                            UnicodeRange = "0000-007F;0080-00FF;0100-017F;1EA0-1EFF"
                        },
                        new
                        {
                            Id = new Guid("cdb3bdd0-77e4-2ed8-766d-a05ebda50ccb"),
                            Code = "ko",
                            IsActive = false,
                            Name = "Korean",
                            UnicodeRange = "AC00-D7AF;1100-11FF;3130-318F;FFA0-FFDC"
                        },
                        new
                        {
                            Id = new Guid("705f22ad-0278-11ba-8c22-987186dd38e8"),
                            Code = "fr",
                            IsActive = false,
                            Name = "French",
                            UnicodeRange = "0000-007F;0080-00FF;0100-017F"
                        },
                        new
                        {
                            Id = new Guid("6e1c9b52-ffaf-343f-bcda-64708f72586d"),
                            Code = "mr",
                            IsActive = false,
                            Name = "Marathi",
                            UnicodeRange = "0900-097F;A8E0-A8FF"
                        },
                        new
                        {
                            Id = new Guid("130867f0-0902-b369-9ff8-d85744b40400"),
                            Code = "ta",
                            IsActive = false,
                            Name = "Tamil",
                            UnicodeRange = "0B80-0BFF"
                        },
                        new
                        {
                            Id = new Guid("bd2b61c1-faeb-4645-7e8a-b814e08daff1"),
                            Code = "tr",
                            IsActive = false,
                            Name = "Turkish",
                            UnicodeRange = "0000-007F;0080-00FF;0100-017F"
                        },
                        new
                        {
                            Id = new Guid("6de0e84b-bc27-e1a7-828f-2fa9a49ca985"),
                            Code = "it",
                            IsActive = false,
                            Name = "Italian",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("89c7dd43-eabc-7741-a147-91f6c9a03b28"),
                            Code = "th",
                            IsActive = false,
                            Name = "Thai",
                            UnicodeRange = "0E00-0E7F"
                        },
                        new
                        {
                            Id = new Guid("3393a5d1-e5c7-0562-fed9-bda9da34b201"),
                            Code = "gu",
                            IsActive = false,
                            Name = "Gujarati",
                            UnicodeRange = "0A80-0AFF"
                        },
                        new
                        {
                            Id = new Guid("49c13280-e4d0-d38a-8ef6-b60289f910cd"),
                            Code = "fa",
                            IsActive = false,
                            Name = "Persian",
                            UnicodeRange = "0600-06FF;0750-077F;FB50-FDFF;FE70-FEFF"
                        },
                        new
                        {
                            Id = new Guid("9b3830c7-d9c8-599e-c867-766babdd48b5"),
                            Code = "pl",
                            IsActive = false,
                            Name = "Polish",
                            UnicodeRange = "0000-007F;0080-00FF;0100-017F"
                        },
                        new
                        {
                            Id = new Guid("1b704476-a4a4-fc9e-8d45-7334dd1480cf"),
                            Code = "ps",
                            IsActive = false,
                            Name = "Pashto",
                            UnicodeRange = "0600-06FF;0750-077F;FB50-FDFF;FE70-FEFF"
                        },
                        new
                        {
                            Id = new Guid("dc1f516b-8ae4-2774-4a35-e3365e36230c"),
                            Code = "kn",
                            IsActive = false,
                            Name = "Kannada",
                            UnicodeRange = "0C80-0CFF"
                        },
                        new
                        {
                            Id = new Guid("75a2b5f9-45bc-626b-ad13-e4a537f62a3b"),
                            Code = "ml",
                            IsActive = false,
                            Name = "Malayalam",
                            UnicodeRange = "0D00-0D7F"
                        },
                        new
                        {
                            Id = new Guid("07ba433f-bf05-1e77-a5d7-4a7a2e8b40c0"),
                            Code = "su",
                            IsActive = false,
                            Name = "Sundanese",
                            UnicodeRange = "1B80-1BBF;0000-007F"
                        },
                        new
                        {
                            Id = new Guid("97d69375-a3bf-98e7-e23b-ecb86cbf3503"),
                            Code = "ha",
                            IsActive = false,
                            Name = "Hausa",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("f9657d62-4515-8f8d-2e10-c40cc38fab62"),
                            Code = "or",
                            IsActive = false,
                            Name = "Odia",
                            UnicodeRange = "0B00-0B7F"
                        },
                        new
                        {
                            Id = new Guid("a0068ec9-050f-1d51-f3d6-f2cfd610cb70"),
                            Code = "my",
                            IsActive = false,
                            Name = "Burmese",
                            UnicodeRange = "1000-109F;AA60-AA7F"
                        },
                        new
                        {
                            Id = new Guid("c16f8ae7-d64a-7a4f-7838-6b20568ce95b"),
                            Code = "uk",
                            IsActive = false,
                            Name = "Ukrainian",
                            UnicodeRange = "0400-04FF"
                        },
                        new
                        {
                            Id = new Guid("aabfe6d8-3770-8f8d-1f44-11816036927e"),
                            Code = "bho",
                            IsActive = false,
                            Name = "Bhojpuri",
                            UnicodeRange = "0900-097F"
                        },
                        new
                        {
                            Id = new Guid("1273e9fe-426d-9a38-c960-82e9ca6961fa"),
                            Code = "tl",
                            IsActive = false,
                            Name = "Tagalog",
                            UnicodeRange = "0000-007F;1700-171F"
                        },
                        new
                        {
                            Id = new Guid("c0f49fce-0d41-af35-bc22-06ab23c8759d"),
                            Code = "yo",
                            IsActive = false,
                            Name = "Yoruba",
                            UnicodeRange = "0000-007F;0080-00FF;0100-017F"
                        },
                        new
                        {
                            Id = new Guid("8a6d600c-16ee-dd70-6ea5-81d6cf3c1490"),
                            Code = "mai",
                            IsActive = false,
                            Name = "Maithili",
                            UnicodeRange = "0900-097F"
                        },
                        new
                        {
                            Id = new Guid("47f520ca-f6f2-bf5d-6d23-b0395419dd43"),
                            Code = "uz",
                            IsActive = false,
                            Name = "Uzbek",
                            UnicodeRange = "0000-007F;0080-00FF;0100-017F"
                        },
                        new
                        {
                            Id = new Guid("9cf036ff-d9e3-b326-7729-48a4f72144dd"),
                            Code = "sd",
                            IsActive = false,
                            Name = "Sindhi",
                            UnicodeRange = "0600-06FF;0900-097F"
                        },
                        new
                        {
                            Id = new Guid("f5b82228-c2aa-1a19-fe53-4140a6629eea"),
                            Code = "am",
                            IsActive = false,
                            Name = "Amharic",
                            UnicodeRange = "1200-137F;1380-139F;2D80-2DDF"
                        },
                        new
                        {
                            Id = new Guid("46eee5f7-6ad2-b97a-9e04-41dc3981cfdf"),
                            Code = "ff",
                            IsActive = false,
                            Name = "Fulani",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("4e39a7ef-a7ca-70fc-76a9-da13a77236b8"),
                            Code = "ro",
                            IsActive = false,
                            Name = "Romanian",
                            UnicodeRange = "0000-007F;0080-00FF;0100-017F"
                        },
                        new
                        {
                            Id = new Guid("41449857-5765-df28-e9c7-cc33e12dfa4c"),
                            Code = "om",
                            IsActive = false,
                            Name = "Oromo",
                            UnicodeRange = "0000-007F;0080-00FF;1200-137F"
                        },
                        new
                        {
                            Id = new Guid("79b555c5-26aa-922e-dbdf-0fed7f7638ee"),
                            Code = "ig",
                            IsActive = false,
                            Name = "Igbo",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("b256339f-0a7d-cb76-5f0c-eea9e80a6e72"),
                            Code = "az",
                            IsActive = false,
                            Name = "Azerbaijani",
                            UnicodeRange = "0000-007F;0080-00FF;0100-017F;0250-02AF"
                        },
                        new
                        {
                            Id = new Guid("bda64eb9-33af-ba1e-45e8-96cbf7ba6f1f"),
                            Code = "awa",
                            IsActive = false,
                            Name = "Awadhi",
                            UnicodeRange = "0900-097F"
                        },
                        new
                        {
                            Id = new Guid("15ac3458-7ad3-d4e7-8a51-83fd5d5020ab"),
                            Code = "ceb",
                            IsActive = false,
                            Name = "Cebuano",
                            UnicodeRange = "0000-007F"
                        },
                        new
                        {
                            Id = new Guid("7e36bf68-8f22-ba45-83cb-8831a5ee6447"),
                            Code = "nl",
                            IsActive = false,
                            Name = "Dutch",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("f9c03ef3-dd81-1094-e1e0-ebc9da2c4b5e"),
                            Code = "ku",
                            IsActive = false,
                            Name = "Kurdish",
                            UnicodeRange = "0000-007F;0080-00FF;0600-06FF"
                        },
                        new
                        {
                            Id = new Guid("c5015305-bc6a-dd82-3a81-ea3810ad0599"),
                            Code = "sr",
                            IsActive = false,
                            Name = "Serbian",
                            UnicodeRange = "0400-04FF;0000-007F"
                        },
                        new
                        {
                            Id = new Guid("bb640f00-bbdb-ac74-a435-5df9f3cfad78"),
                            Code = "mg",
                            IsActive = false,
                            Name = "Malagasy",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("f0107ed5-4e47-0e5d-f552-beb0dedd033b"),
                            Code = "skr",
                            IsActive = false,
                            Name = "Saraiki",
                            UnicodeRange = "0600-06FF;0750-077F"
                        },
                        new
                        {
                            Id = new Guid("77f0532f-96d3-f032-b325-d5eabfc8798b"),
                            Code = "ne",
                            IsActive = false,
                            Name = "Nepali",
                            UnicodeRange = "0900-097F"
                        },
                        new
                        {
                            Id = new Guid("e254332a-0ed5-bfc4-80ba-1fbcd253506e"),
                            Code = "si",
                            IsActive = false,
                            Name = "Sinhala",
                            UnicodeRange = "0D80-0DFF"
                        },
                        new
                        {
                            Id = new Guid("c9d92254-c7ce-f352-abda-e0263b0934ed"),
                            Code = "ctg",
                            IsActive = false,
                            Name = "Chittagonian",
                            UnicodeRange = "0980-09FF"
                        },
                        new
                        {
                            Id = new Guid("dfaa9b83-24b7-6ee0-ac3b-12a431dd8358"),
                            Code = "za",
                            IsActive = false,
                            Name = "Zhuang",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("ba4e569f-9cbc-b9f0-589b-4ecf6228379a"),
                            Code = "km",
                            IsActive = false,
                            Name = "Khmer",
                            UnicodeRange = "1780-17FF;19E0-19FF"
                        },
                        new
                        {
                            Id = new Guid("9211126f-b39e-880a-188a-f058eb7dbcfb"),
                            Code = "tk",
                            IsActive = false,
                            Name = "Turkmen",
                            UnicodeRange = "0000-007F;0080-00FF;0100-017F"
                        },
                        new
                        {
                            Id = new Guid("222a837e-3736-3a2b-c5e0-30c551d90bab"),
                            Code = "as",
                            IsActive = false,
                            Name = "Assamese",
                            UnicodeRange = "0980-09FF"
                        },
                        new
                        {
                            Id = new Guid("3dbe972d-6692-1f14-e879-08a0e213c09f"),
                            Code = "mad",
                            IsActive = false,
                            Name = "Madurese",
                            UnicodeRange = "0000-007F"
                        },
                        new
                        {
                            Id = new Guid("a54d100b-9473-4797-64cc-7b3a42f2c1de"),
                            Code = "so",
                            IsActive = false,
                            Name = "Somali",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("fe7ee7a5-961a-ddeb-ec93-a38680791bf4"),
                            Code = "mwr",
                            IsActive = false,
                            Name = "Marwari",
                            UnicodeRange = "0900-097F"
                        },
                        new
                        {
                            Id = new Guid("be2094bf-80f7-cf23-6e9a-b6ed3f67ada9"),
                            Code = "mag",
                            IsActive = false,
                            Name = "Magahi",
                            UnicodeRange = "0900-097F"
                        },
                        new
                        {
                            Id = new Guid("e2e34403-efe6-3b15-d3b1-d4ecded8f8c9"),
                            Code = "bgc",
                            IsActive = false,
                            Name = "Haryanvi",
                            UnicodeRange = "0900-097F"
                        },
                        new
                        {
                            Id = new Guid("2e11867b-40c6-d81f-f06a-b5251d1a68fe"),
                            Code = "hu",
                            IsActive = false,
                            Name = "Hungarian",
                            UnicodeRange = "0000-007F;0080-00FF;0100-017F"
                        },
                        new
                        {
                            Id = new Guid("639a4f74-411b-b2e8-8e48-0b30ac012d21"),
                            Code = "hne",
                            IsActive = false,
                            Name = "Chhattisgarhi",
                            UnicodeRange = "0900-097F"
                        },
                        new
                        {
                            Id = new Guid("97a4af0a-7d80-c95a-b509-656bd13b5283"),
                            Code = "el",
                            IsActive = false,
                            Name = "Greek",
                            UnicodeRange = "0370-03FF;1F00-1FFF"
                        },
                        new
                        {
                            Id = new Guid("9d237997-3ac3-cb5f-9773-0b8be66c1f59"),
                            Code = "ny",
                            IsActive = false,
                            Name = "Chewa",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("a2ce43dd-1ac4-cc54-6536-8193e2343bf9"),
                            Code = "ak",
                            IsActive = false,
                            Name = "Akan",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("27e65ad0-c8fc-e708-df1e-e341c3d5cbc2"),
                            Code = "kk",
                            IsActive = false,
                            Name = "Kazakh",
                            UnicodeRange = "0400-04FF"
                        },
                        new
                        {
                            Id = new Guid("788311b2-f7fb-c0f4-57b6-686207960f37"),
                            Code = "syl",
                            IsActive = false,
                            Name = "Sylheti",
                            UnicodeRange = "A800-A82F"
                        },
                        new
                        {
                            Id = new Guid("33670468-65e4-6591-a4f5-9a1918cb1408"),
                            Code = "zu",
                            IsActive = false,
                            Name = "Zulu",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("8044ff83-f2cd-0a90-e83b-f30d95774d76"),
                            Code = "cs",
                            IsActive = false,
                            Name = "Czech",
                            UnicodeRange = "0000-007F;0080-00FF;0100-017F"
                        },
                        new
                        {
                            Id = new Guid("325987e4-cfc8-2b3d-4232-34a1d35b15e0"),
                            Code = "rw",
                            IsActive = false,
                            Name = "Kinyarwanda",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("f2edb282-346e-097b-5177-f699237327c2"),
                            Code = "dhd",
                            IsActive = false,
                            Name = "Dhundhari",
                            UnicodeRange = "0900-097F"
                        },
                        new
                        {
                            Id = new Guid("7dec9973-4a74-f90b-18af-8a1975bebeca"),
                            Code = "ht",
                            IsActive = false,
                            Name = "Haitian Creole",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("8a829935-f84a-ecea-0992-e0a4499e5fb2"),
                            Code = "ilo",
                            IsActive = false,
                            Name = "Ilocano",
                            UnicodeRange = "0000-007F"
                        },
                        new
                        {
                            Id = new Guid("fbc50d05-ed2c-eef3-f331-0a88820ecaa0"),
                            Code = "qu",
                            IsActive = false,
                            Name = "Quechua",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("ce82fee6-840d-ee02-bb9d-8c987e9eb2a3"),
                            Code = "rn",
                            IsActive = false,
                            Name = "Kirundi",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("0f1a1741-36cd-e92c-8b5f-0f11398713b6"),
                            Code = "sv",
                            IsActive = false,
                            Name = "Swedish",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("495be493-a892-2948-fce5-681feeb81782"),
                            Code = "hmn",
                            IsActive = false,
                            Name = "Hmong",
                            UnicodeRange = "0000-007F;16B00-16B8F"
                        },
                        new
                        {
                            Id = new Guid("6266d16c-8654-fb44-2621-f46c01701334"),
                            Code = "sn",
                            IsActive = false,
                            Name = "Shona",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("3339d5bf-37a2-a8c0-fcaf-96f998036ff6"),
                            Code = "ug",
                            IsActive = false,
                            Name = "Uyghur",
                            UnicodeRange = "0600-06FF;0750-077F"
                        },
                        new
                        {
                            Id = new Guid("bb933266-1f74-fd93-e4a3-e63d58fb2166"),
                            Code = "hil",
                            IsActive = false,
                            Name = "Hiligaynon",
                            UnicodeRange = "0000-007F"
                        },
                        new
                        {
                            Id = new Guid("98ab275d-9bea-f873-dddc-c2ccb35f7cdd"),
                            Code = "mos",
                            IsActive = false,
                            Name = "Mossi",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("a019ab66-49e3-5b4a-e559-8b106d98d651"),
                            Code = "xh",
                            IsActive = false,
                            Name = "Xhosa",
                            UnicodeRange = "0000-007F;0080-00FF"
                        },
                        new
                        {
                            Id = new Guid("46e46d0a-9500-98f3-e8a4-5ed512a7538f"),
                            Code = "be",
                            IsActive = false,
                            Name = "Belarusian",
                            UnicodeRange = "0400-04FF"
                        },
                        new
                        {
                            Id = new Guid("3d7df04d-0fc3-7000-3a69-bc8112e0c100"),
                            Code = "bal",
                            IsActive = false,
                            Name = "Balochi",
                            UnicodeRange = "0600-06FF;0750-077F"
                        },
                        new
                        {
                            Id = new Guid("de592a60-60fb-29b6-4f92-05bd6834c18a"),
                            Code = "kok",
                            IsActive = false,
                            Name = "Konkani",
                            UnicodeRange = "0900-097F"
                        },
                        new
                        {
                            Id = new Guid("3d75c0ad-6437-d11e-17f7-b999a0ae79a0"),
                            Code = "ka",
                            IsActive = false,
                            Name = "Georgian",
                            UnicodeRange = "10A0-10FF;2D00-2D2F"
                        });
                });

            modelBuilder.Entity("Translator.Domain.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("hash");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_templates_owner_id");

                    b.HasIndex("Hash", "OwnerId")
                        .IsUnique()
                        .HasDatabaseName("ix_templates_hash_owner_id");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("Translator.Domain.Entities.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<Guid>("TemplateValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_value_id");

                    b.Property<string>("TranslationValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("translation_value");

                    b.HasKey("Id")
                        .HasName("pk_translations");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_translations_language_id");

                    b.HasIndex("TemplateValueId")
                        .HasDatabaseName("ix_translations_template_value_id");

                    b.ToTable("translations", (string)null);
                });

            modelBuilder.Entity("Translator.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("secret_key");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("SecretKey")
                        .IsUnique()
                        .HasDatabaseName("ix_users_secret_key");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Translator.Domain.Entities.Value", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hash");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.HasKey("Id")
                        .HasName("pk_values");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_values_owner_id");

                    b.HasIndex("Hash", "OwnerId")
                        .IsUnique()
                        .HasDatabaseName("ix_values_hash_owner_id");

                    b.ToTable("values", (string)null);
                });

            modelBuilder.Entity("TemplateValue", b =>
                {
                    b.HasOne("Translator.Domain.Entities.Template", null)
                        .WithMany()
                        .HasForeignKey("TemplatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_values_templates_templates_id");

                    b.HasOne("Translator.Domain.Entities.Value", null)
                        .WithMany()
                        .HasForeignKey("ValuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_values_values_values_id");
                });

            modelBuilder.Entity("Translator.Domain.Entities.Category", b =>
                {
                    b.HasOne("Translator.Domain.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_categories_categories_parent_id");

                    b.HasOne("Translator.Domain.Entities.CategoryType", "Type")
                        .WithMany("Categories")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categories_category_types_type_id");

                    b.Navigation("Parent");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Translator.Domain.Entities.Template", b =>
                {
                    b.HasOne("Translator.Domain.Entities.User", "Owner")
                        .WithMany("Templates")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_templates_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Translator.Domain.Entities.Translation", b =>
                {
                    b.HasOne("Translator.Domain.Entities.Language", "Language")
                        .WithMany("Translations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_translations_languages_language_id");

                    b.HasOne("Translator.Domain.Entities.Value", "Value")
                        .WithMany("Translations")
                        .HasForeignKey("TemplateValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_translations_values_template_value_id");

                    b.Navigation("Language");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("Translator.Domain.Entities.Value", b =>
                {
                    b.HasOne("Translator.Domain.Entities.User", "Owner")
                        .WithMany("Values")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_values_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Translator.Domain.Entities.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Translator.Domain.Entities.CategoryType", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Translator.Domain.Entities.Language", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Translator.Domain.Entities.User", b =>
                {
                    b.Navigation("Templates");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("Translator.Domain.Entities.Value", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
