// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Translator.Infrastructure.Database.Postgres;

#nullable disable

namespace Translator.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Translator.Domain.DataModels.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("UnicodeRange")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("unicode_range");

                    b.HasKey("Id")
                        .HasName("pk_language");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_language_code");

                    b.ToTable("language", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c76abc4b-5ede-0523-42a5-e78b4cf1614c"),
                            Code = "en",
                            IsActive = false,
                            Name = "Basic Latin",
                            UnicodeRange = "0000-007F"
                        },
                        new
                        {
                            Id = new Guid("0dee066e-20ac-76ef-16ad-7d1d547d1b34"),
                            Code = "mr",
                            IsActive = false,
                            Name = "Spacing Modifier Letters",
                            UnicodeRange = "02B0-02FF"
                        },
                        new
                        {
                            Id = new Guid("c8d85589-9764-2a3a-0d58-7a064e7379b5"),
                            Code = "el",
                            IsActive = false,
                            Name = "Greek and Coptic",
                            UnicodeRange = "0370-03FF"
                        },
                        new
                        {
                            Id = new Guid("9131af4b-e843-7b25-c8f7-061e54525078"),
                            Code = "ru",
                            IsActive = false,
                            Name = "Cyrillic",
                            UnicodeRange = "0400-04FF"
                        },
                        new
                        {
                            Id = new Guid("d3ed97b3-7757-f6a9-0361-19e6ced96ff6"),
                            Code = "hy",
                            IsActive = false,
                            Name = "Armenian",
                            UnicodeRange = "0530-058F"
                        },
                        new
                        {
                            Id = new Guid("1af8c1c6-6646-8563-fa7d-85df7eaf8763"),
                            Code = "he",
                            IsActive = false,
                            Name = "Hebrew",
                            UnicodeRange = "0590-05FF"
                        },
                        new
                        {
                            Id = new Guid("85cb2c27-ba92-e0fd-baf1-dedce0fd3ac2"),
                            Code = "ar",
                            IsActive = false,
                            Name = "Arabic",
                            UnicodeRange = "0600-06FF"
                        },
                        new
                        {
                            Id = new Guid("bec6cfb4-6fc9-54cb-6504-55f269f39b71"),
                            Code = "syc",
                            IsActive = false,
                            Name = "Syriac",
                            UnicodeRange = "0700-074F"
                        },
                        new
                        {
                            Id = new Guid("16ad1b7f-58db-70be-c295-9aab31dd5d86"),
                            Code = "dv",
                            IsActive = false,
                            Name = "Thaana",
                            UnicodeRange = "0780-07BF"
                        },
                        new
                        {
                            Id = new Guid("e2f8815d-6c09-cd99-6c2a-83a1166f29ad"),
                            Code = "nqo",
                            IsActive = false,
                            Name = "NKo",
                            UnicodeRange = "07C0-07FF"
                        },
                        new
                        {
                            Id = new Guid("86c52e42-de6b-c50f-eaf6-9b3651080bd9"),
                            Code = "hi",
                            IsActive = false,
                            Name = "Devanagari",
                            UnicodeRange = "0900-097F"
                        },
                        new
                        {
                            Id = new Guid("84cb6da5-c243-8e5f-14b4-7b8ff1748331"),
                            Code = "bn",
                            IsActive = false,
                            Name = "Bengali",
                            UnicodeRange = "0980-09FF"
                        },
                        new
                        {
                            Id = new Guid("043f9914-0813-6885-a59d-a0a92c8f0696"),
                            Code = "pa",
                            IsActive = false,
                            Name = "Gurmukhi",
                            UnicodeRange = "0A00-0A7F"
                        },
                        new
                        {
                            Id = new Guid("3393a5d1-e5c7-0562-fed9-bda9da34b201"),
                            Code = "gu",
                            IsActive = false,
                            Name = "Gujarati",
                            UnicodeRange = "0A80-0AFF"
                        },
                        new
                        {
                            Id = new Guid("57be1faa-cc7e-ca29-7b97-0d4151dfe682"),
                            Code = "or",
                            IsActive = false,
                            Name = "Oriya",
                            UnicodeRange = "0B00-0B7F"
                        },
                        new
                        {
                            Id = new Guid("130867f0-0902-b369-9ff8-d85744b40400"),
                            Code = "ta",
                            IsActive = false,
                            Name = "Tamil",
                            UnicodeRange = "0B80-0BFF"
                        },
                        new
                        {
                            Id = new Guid("888ab815-cfe6-a416-462c-1562fdcb0c19"),
                            Code = "te",
                            IsActive = false,
                            Name = "Telugu",
                            UnicodeRange = "0C00-0C7F"
                        },
                        new
                        {
                            Id = new Guid("dc1f516b-8ae4-2774-4a35-e3365e36230c"),
                            Code = "kn",
                            IsActive = false,
                            Name = "Kannada",
                            UnicodeRange = "0C80-0CFF"
                        },
                        new
                        {
                            Id = new Guid("75a2b5f9-45bc-626b-ad13-e4a537f62a3b"),
                            Code = "ml",
                            IsActive = false,
                            Name = "Malayalam",
                            UnicodeRange = "0D00-0D7F"
                        },
                        new
                        {
                            Id = new Guid("e254332a-0ed5-bfc4-80ba-1fbcd253506e"),
                            Code = "si",
                            IsActive = false,
                            Name = "Sinhala",
                            UnicodeRange = "0D80-0DFF"
                        },
                        new
                        {
                            Id = new Guid("89c7dd43-eabc-7741-a147-91f6c9a03b28"),
                            Code = "th",
                            IsActive = false,
                            Name = "Thai",
                            UnicodeRange = "0E00-0E7F"
                        },
                        new
                        {
                            Id = new Guid("d356fdd8-06ba-de72-0f66-25bfb1b4ca7b"),
                            Code = "lo",
                            IsActive = false,
                            Name = "Lao",
                            UnicodeRange = "0E80-0EFF"
                        },
                        new
                        {
                            Id = new Guid("33f941a4-02e0-556f-ccff-38b534f98a53"),
                            Code = "bo",
                            IsActive = false,
                            Name = "Tibetan",
                            UnicodeRange = "0F00-0FFF"
                        },
                        new
                        {
                            Id = new Guid("4ca57f21-35c9-0415-fcde-32147bff005d"),
                            Code = "my",
                            IsActive = false,
                            Name = "Myanmar",
                            UnicodeRange = "1000-109F"
                        },
                        new
                        {
                            Id = new Guid("3d75c0ad-6437-d11e-17f7-b999a0ae79a0"),
                            Code = "ka",
                            IsActive = false,
                            Name = "Georgian",
                            UnicodeRange = "10A0-10FF"
                        },
                        new
                        {
                            Id = new Guid("bac3dea2-633b-dc59-fdf5-b96d4de71455"),
                            Code = "ko",
                            IsActive = false,
                            Name = "Hangul Jamo",
                            UnicodeRange = "1100-11FF"
                        },
                        new
                        {
                            Id = new Guid("ca97a393-c926-5790-202f-168312e5c7d5"),
                            Code = "am",
                            IsActive = false,
                            Name = "Ethiopic",
                            UnicodeRange = "1200-137F"
                        },
                        new
                        {
                            Id = new Guid("a0df8c3d-a857-197c-1caa-67b1677e376c"),
                            Code = "chr",
                            IsActive = false,
                            Name = "Cherokee",
                            UnicodeRange = "13A0-13FF"
                        },
                        new
                        {
                            Id = new Guid("13121d03-b2bd-9831-df28-7449fdbd1afb"),
                            Code = "cr",
                            IsActive = false,
                            Name = "Unified Canadian Aboriginal Syllabics",
                            UnicodeRange = "1400-167F"
                        },
                        new
                        {
                            Id = new Guid("b394563e-9fd8-54a1-e9af-34b1fc6f0ce7"),
                            Code = "non",
                            IsActive = false,
                            Name = "Runic",
                            UnicodeRange = "16A0-16FF"
                        },
                        new
                        {
                            Id = new Guid("1273e9fe-426d-9a38-c960-82e9ca6961fa"),
                            Code = "tl",
                            IsActive = false,
                            Name = "Tagalog",
                            UnicodeRange = "1700-171F"
                        },
                        new
                        {
                            Id = new Guid("c0396d8b-f79f-54ec-4e5e-6e3949a29b1f"),
                            Code = "zh",
                            IsActive = false,
                            Name = "Hanunoo",
                            UnicodeRange = "1720-173F"
                        },
                        new
                        {
                            Id = new Guid("ba4e569f-9cbc-b9f0-589b-4ecf6228379a"),
                            Code = "km",
                            IsActive = false,
                            Name = "Khmer",
                            UnicodeRange = "1780-17FF"
                        },
                        new
                        {
                            Id = new Guid("054fc828-c5db-ff21-a522-20ce03b16356"),
                            Code = "mn",
                            IsActive = false,
                            Name = "Mongolian",
                            UnicodeRange = "1800-18AF"
                        },
                        new
                        {
                            Id = new Guid("07ba433f-bf05-1e77-a5d7-4a7a2e8b40c0"),
                            Code = "su",
                            IsActive = false,
                            Name = "Sundanese",
                            UnicodeRange = "1B80-1BBF"
                        },
                        new
                        {
                            Id = new Guid("61200e30-f81c-9040-3229-25e1a4f72c2d"),
                            Code = "sat",
                            IsActive = false,
                            Name = "Ol Chiki",
                            UnicodeRange = "1C50-1C7F"
                        },
                        new
                        {
                            Id = new Guid("99946b14-bc40-20d4-ae08-9773a8051903"),
                            Code = "cu",
                            IsActive = false,
                            Name = "Glagolitic",
                            UnicodeRange = "2C00-2C5F"
                        },
                        new
                        {
                            Id = new Guid("8b154491-2019-84a0-e125-a1e4f7f632b2"),
                            Code = "ber",
                            IsActive = false,
                            Name = "Tifinagh",
                            UnicodeRange = "2D30-2D7F"
                        },
                        new
                        {
                            Id = new Guid("8697668a-7cc7-2982-44af-012803ce7ab5"),
                            Code = "ja",
                            IsActive = false,
                            Name = "Hiragana",
                            UnicodeRange = "3040-309F"
                        },
                        new
                        {
                            Id = new Guid("a988ef13-d894-8657-69d2-e77a6de2f287"),
                            Code = "ii",
                            IsActive = false,
                            Name = "Yijing Hexagram Symbols",
                            UnicodeRange = "4DC0-4DFF"
                        },
                        new
                        {
                            Id = new Guid("aa56b1a0-8c68-b0fc-babd-6e866e766521"),
                            Code = "lis",
                            IsActive = false,
                            Name = "Lisu",
                            UnicodeRange = "A4D0-A4FF"
                        },
                        new
                        {
                            Id = new Guid("a257f3da-1a5d-cd1e-206f-3e3dc505f4c2"),
                            Code = "vai",
                            IsActive = false,
                            Name = "Vai",
                            UnicodeRange = "A500-A63F"
                        },
                        new
                        {
                            Id = new Guid("0fd12294-475b-c6ec-1ebf-221545cb1420"),
                            Code = "syl",
                            IsActive = false,
                            Name = "Syloti Nagri",
                            UnicodeRange = "A800-A82F"
                        },
                        new
                        {
                            Id = new Guid("6daf947d-eacc-73d2-6bd1-d456ba3c750a"),
                            Code = "jv",
                            IsActive = false,
                            Name = "Javanese",
                            UnicodeRange = "A980-A9DF"
                        },
                        new
                        {
                            Id = new Guid("2343f32f-acbb-8290-6743-1c6af2da2884"),
                            Code = "cja",
                            IsActive = false,
                            Name = "Cham",
                            UnicodeRange = "AA00-AA5F"
                        },
                        new
                        {
                            Id = new Guid("19a02285-fe10-c443-6204-1b4451ca6ad2"),
                            Code = "mni",
                            IsActive = false,
                            Name = "Meetei Mayek Extensions",
                            UnicodeRange = "AAE0-AAFF"
                        },
                        new
                        {
                            Id = new Guid("32b3e701-0748-de76-57da-01822d0d6a76"),
                            Code = "peo",
                            IsActive = false,
                            Name = "Old Persian",
                            UnicodeRange = "103A0-103DF"
                        },
                        new
                        {
                            Id = new Guid("9d37f00c-1d50-d551-f961-ee306c842157"),
                            Code = "so",
                            IsActive = false,
                            Name = "Osmanya",
                            UnicodeRange = "10480-104AF"
                        },
                        new
                        {
                            Id = new Guid("66643064-4a7b-779c-4180-bc4926f411e6"),
                            Code = "phn",
                            IsActive = false,
                            Name = "Phoenician",
                            UnicodeRange = "10900-1091F"
                        },
                        new
                        {
                            Id = new Guid("c63ddf57-f0b6-3cbe-0879-cfb539b61169"),
                            Code = "sd",
                            IsActive = false,
                            Name = "Khudawadi",
                            UnicodeRange = "112B0-112FF"
                        },
                        new
                        {
                            Id = new Guid("6bee55d0-420f-dc8c-46d1-088080692a29"),
                            Code = "mai",
                            IsActive = false,
                            Name = "Tirhuta",
                            UnicodeRange = "11480-114DF"
                        },
                        new
                        {
                            Id = new Guid("1b69af13-a92b-e967-10e6-8c3dacee3db2"),
                            Code = "doi",
                            IsActive = false,
                            Name = "Takri",
                            UnicodeRange = "11680-116CF"
                        },
                        new
                        {
                            Id = new Guid("bff4d41e-a13d-5cfa-2992-d62659dcd91f"),
                            Code = "hoc",
                            IsActive = false,
                            Name = "Warang Citi",
                            UnicodeRange = "118A0-118FF"
                        },
                        new
                        {
                            Id = new Guid("a2f907d3-caba-22c2-dad2-d388d32bf4b3"),
                            Code = "xng",
                            IsActive = false,
                            Name = "Zanabazar Square",
                            UnicodeRange = "11A00-11A4F"
                        });
                });

            modelBuilder.Entity("Translator.Domain.DataModels.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Hash")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("hash");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_template");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_template_hash");

                    b.ToTable("template", (string)null);
                });

            modelBuilder.Entity("Translator.Domain.DataModels.TemplateValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.HasKey("Id")
                        .HasName("pk_template_value");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_template_value_hash");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_template_value_template_id");

                    b.ToTable("template_value", (string)null);
                });

            modelBuilder.Entity("Translator.Domain.DataModels.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<Guid>("TemplateValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_value_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_translation");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_translation_language_id");

                    b.HasIndex("TemplateValueId")
                        .HasDatabaseName("ix_translation_template_value_id");

                    b.ToTable("translation", (string)null);
                });

            modelBuilder.Entity("Translator.Domain.DataModels.TemplateValue", b =>
                {
                    b.HasOne("Translator.Domain.DataModels.Template", "Template")
                        .WithMany("TemplateValues")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_value_template_template_id");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Translator.Domain.DataModels.Translation", b =>
                {
                    b.HasOne("Translator.Domain.DataModels.Language", "Language")
                        .WithMany("Translations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_translation_language_language_id");

                    b.HasOne("Translator.Domain.DataModels.TemplateValue", "TemplateValue")
                        .WithMany("Translations")
                        .HasForeignKey("TemplateValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_translation_template_value_template_value_id");

                    b.Navigation("Language");

                    b.Navigation("TemplateValue");
                });

            modelBuilder.Entity("Translator.Domain.DataModels.Language", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Translator.Domain.DataModels.Template", b =>
                {
                    b.Navigation("TemplateValues");
                });

            modelBuilder.Entity("Translator.Domain.DataModels.TemplateValue", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
